# Generated by Django 4.0.3 on 2022-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=50)),
                ('services_desc', models.TextField()),
            ],
        ),
    ]
